### ISSUE TITLE
Is there an API to implement custom service? (rest, etc)

### ISSUE THREAD

**Issue by jswigart** [twofas/2fas-server#1]
I tried to submit this through the contact us popup form from the website, but clicking "Send Message" did not work. Hope this is ok here.

Hello, I am a game developer who is considering using 2fas as an authenticator for a web based admin page accessible for a running game server.

The server is written in C#, so would presumably need to hit a back-end API endpoints for 2fas to direct users to a QR code, and then later to validate keys.

I started implementing this functionality with Google Authenticator, as there is a really easy C# package on nuget for it https://github.com/NickyBall/GoogleAuthenticatorService.Core

But I like what 2fas offers as far as the browser extension and stuff that will make it easier on server operators.

I was wondering if yall have API support(endpoints, etc) that might facilitate hooking up a 'custom service' like this?

Thanks
Jeremy

**Comment by 2fas-com** [comment]
Hi Jeremy!

Thank you for your suggestion! For now, we do not have the endpoints you're asking about. We'll talk it through tho! We'll let you know if we decide to implement this.

Have a great day!
