### ISSUE TITLE
2FA code in trash that was used previously prevents new code outside of trash from being used?

### ISSUE THREAD

**Issue by jikamens** [twofas/2fas-server#7]
LastPass just made me reset my 2FA. I did the following:

1. Scanned new QR code in 2FAS Android.
2. Entered TOTP CODE by hand into LastPass to confirm the new TOTP seed.
3. Trashed the old LastPass entry in 2FAS Android.
4. Tried to log into LastPass again to confirm everything was working.
5. When prompted for my 2FAS code, sent a request to 2FAS.
6. 2FAS said there was an error sending the code.

2FAS refused to start sending the code to LastPass until I removed the old LastPass item from my trash in the 2FAS app.

**Comment by KobeW50** [comment]
Hi @jikamens, I believe this issue should be reported in the [2FAS-Android repository](https://github.com/twofas/2fas-android/issues) as it sounds like the issue is local and isn't caused by an issue with the server. Please reopen this issue in that repository. Thank you
